# Generated by Django 3.0.3 on 2020-02-16 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
