# Generated by Django 3.0.3 on 2020-03-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200315_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
