# Generated by Django 3.0.3 on 2020-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TrainerSpecialty',
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='specialities',
            field=models.ManyToManyField(to='users.TrainerSpeciality'),
        ),
    ]
