# Generated by Django 3.0.3 on 2020-05-31 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200322_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'Trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
