# Generated by Django 3.0.3 on 2020-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200531_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
