# Generated by Django 3.0.3 on 2020-02-19 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='attendees',
            field=models.ManyToManyField(related_name='attendance', through='core.Attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
