# Generated by Django 3.0.3 on 2020-03-15 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='attendees',
            field=models.ManyToManyField(related_name='attendance', through='core.Attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_classes', to='core.WorkoutCategory'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'Trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_in_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendee',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GymClass'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
