# Generated by Django 3.0.3 on 2020-05-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personaltraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltraining',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
