# Generated by Django 3.0.3 on 2020-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personaltraining_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltraining',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
