# Generated by Django 3.0.3 on 2020-05-31 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_personaltraining_google_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltraining',
            name='gym_member',
            field=models.ForeignKey(limit_choices_to={'role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, related_name='member_personal_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaltraining',
            name='gym_trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'Trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_personal_trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
