# Generated by Django 3.0.3 on 2020-05-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200531_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltraining',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='personaltraining',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
    ]
