# Generated by Django 3.0.3 on 2020-06-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200604_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltraining',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaltraining',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
