# Generated by Django 3.0.3 on 2020-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200604_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltraining',
            name='member_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
