# Generated by Django 3.0.3 on 2020-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_personaltraining_member_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltraining',
            name='gloves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaltraining',
            name='transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaltraining',
            name='weights',
            field=models.BooleanField(default=False),
        ),
    ]
