# Generated by Django 3.0.3 on 2020-11-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200914_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltraining',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
